name: Check Changed Files are all python files
on: [push, pull_request]

# Idea here is to prevent any changes which can prevent repository workflows from running

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history so we can compare with the previous commit

    - name: Check changed files
      run: |
        changed_files=$(git diff --name-only HEAD^ HEAD)
        for file in $changed_files; do
          if [[ ! $file =~ .*\.py$ ]]; then  # Any python file in any directory is allowed
            echo "Error: Changes have been made outside of the allowed directory"
            exit 1
          fi
        done
        