name: Pull Request Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: pr

    - name: Checkout main branch code
      uses: actions/checkout@v2
      with:
        ref: 'main'
        path: main

    - name: Run check script in Docker container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/main:/workspace/main \
          -v ${{ github.workspace }}/pr:/workspace/pr \
          -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
          -e BASE_REPOSITORY="${{ github.repository }}" \
          -e HEAD_REPOSITORY="${{ github.event.pull_request.head.repo.full_name }}" \
          -e HEAD_BRANCH="${{ github.event.pull_request.head.ref }}" \
          datasurface/datasurface:latest \
          python -m datasurface.handler.action /workspace/main /workspace/pr