= Data surface Data Catalog
Data surface uses a unique data catalog implementation. Data catalogs are used to describe data sources and their schemas in a database. There are controls implemented around the data catalog so that provenance can be established for the artifacts stored in the catalog:

* Data sources
* Datasets and their schemas
* Data surface allows data consumers to describe their inputs, engine requirements and regulatory requirements.

== Controls for provenance
Catalogs typically need to define roles, workflows and approval processes. Data surface uses github for these purposes rather than needing a proprietary implementation or such as implementation that can be bridged to workflow or authorization frameworks in use by the enterprise.

== Controlling changes of metadata in Data surface
This section describes how a use can use github to define the major artifacts needed in an implementation. Data surface defines top level artifacts whose changes can be managed by use of github.

* Ecosystem
* Governance Zones
* Teams

== What is an Ecosystem?
An Ecosystem is intended to represent the entirety of a firms data assets. This includes all geographical/regulatory locations, all data platforms, data center hosting providers, cloud providers and internal providers. The ecosystem is defined in a github repository. The CICD in place around who can make changes and who reviews those changes controls the changes to the ecosystem. An Ecosystem is divided in to Governance Zones. 

An Ecoystem is associated with a specific repository to manage changes. The repository must contain a file called *eco.py* which defines the ecosystem. The *eco.py* module be at the root level and must have a method called: *def createEcosystem() -> Ecosystem:* This method must return the primary Ecosystem instance. All objects within that ecosystem should also be filled out on that instance.

Each Governance zone must be authorized by the ecosystem owner before it can be defined.

=== What is a Governance Zone?
Each governance zone is responsible for implementing a set of policies over internal and cloud infrastructure providers and data platforms. All data stores and moved within this zone is governed by the zone policies. Firms might have a US zone, a UK zone, a European Zone and a Chinese zone for example. Data sourced in each zone would be managed by teams local to that one. The zone can define storage policies which control how and where data is stored and where it can be moved.

A Governance zone is associated with a specific repository to manage changes

Each team must be authorized by the governance zone owner before it can be defined.

==== What is a Team?
A team is responsible for an exclusive set of data and consumers of that data. Data is represented as Datastores and consumers are represented as Workspaces.

A team is associated with a specific repository to manage changes

===== Datastores, datasets and capture metadata
Data is represented as Datastores which are collections of Datasets. A dataset can be thought of as a single collection of homegenous data with a common schema describing all records in that dataset. A datastore is a collection of these datasets which are ingested together in to the ecosystem. A single physical database might have several data stores defined on it. Each datastore having datsets corresponding to tables within the database. Each data store is pointed at the same database but may use different credentials for reading the data and use different schedules or approaches for ingesting the data in to the ecosystem.

===== Consuming data, Workspaces and dataplatforms


== Defining an ecosystem
An ecosystem consists of a collection of governancezones. The ecosystem is defined in to main branch of a github repository. The CICD in place around who can make changes and who reviews those changes controls the changes to the ecosystem.
== Defining a Governance Zone
The ecosystem team can allow a new governance zone to be defined. They can add a governancezone declaration to a specific ecosystem. This defines the name of the governance zone as well as the repository which can be used to control changes to all objects for that governance zone. It's important to realize that the way these changes are controlled is not at the file level but instead it's at the model level. Data surface only requires that the ecosystem must be defined in a file called eco.py. It does not define any other file names. Users can use any files they choose.

The *eco.py* module be at the root level and must have a method called:
*def createEcosystem() -> Ecosystem:*
This method must return the primary Ecosystem instance. All objects within that ecosystem should also be filled out on that instance. The ecosystem branch checks the model for validity. It checks:

* That all objects are defined correctly.
* That all references between objects are valid.
* The whole model is consistent.

The main branch defines the steady state of the system, the release version if you want. Other git repositories can be defined on branches or even seperate repositories. Ownership of a subset of the model is assigned to these branches or repositories. When changes are pulled in to the main branch, handlers make sure that the changes result in a consistent model AND that any model changes were made from a git branch or repository that is authorized to make those changes. The system doesn't care which files were modified by which repository. It only cares that the model is consistent and that the model objects were only modified by an authorized repository. Thus, a repository can refactor how the ecosystem is constructed from the eco.py file to a different file structure. The ecosystem branch will only check that the model is consistent and that the objects are only modified by authorized repositories.